### ISSUE TITLE
Regarding the System Path Changes

### ISSUE THREAD

**Issue by ikhsansdqq** [bycloudai/SwapCudaVersionWindows#1]
Hi! Great tips by the way but unfortunately it only change the nvcc and not the CUDA version itself. If you look closely in `nvcc --version` yes it does change to the desired version, but if you use `nvidia-smi` function, it still use the latest version.

**Comment by bycloudai** [comment]
shouldn't be a problem, since they are "unrelated"
You can refer to this thread for more info: https://stackoverflow.com/a/53504578
